#!/usr/bin/env ruby

require 'net/http'

TEAMS_URL = "http://espn.go.com/mens-college-basketball/teams"

def team_url(team)
  body = Net::HTTP.get(URI(TEAMS_URL))
  if body=~ /<a href="([^"]*)" class="bi">#{team}<\/a>/
    URI($1)
  end
end

def print_schedule(uri)
  body = Net::HTTP.get(uri)
  body.scan(/<tr class="(evenrow|oddrow) team-\d{2}-\d+">.+?<\/tr>/) do
    row = $&
    date = row.match(/<td>([A-Z][a-z]{2} \d+)<\/td>/)[1]
    #time = row.match(/<td>(\d+:\d{2} [AP]M {A-Z]{2}|TBD)<\/td>/)[1]
    #puts "#{date}    #{time}"
    puts date  
end
end

def main
  print ">"
  team = gets.chomp
  print "Finding schedule for #{team}..."
  url = team_url(team)
  print url

  if url.nil?
    puts "sorry, team not found"
  else
    print_schedule(url)
end 
main
end

main
